### ISSUE TITLE
Not support aliyun oss internal model

### ISSUE THREAD

**Issue by gotoworld** [fog/fog-aliyun#44]
```
rake aborted!
Excon::Error::Forbidden: Expected(200) <=> Actual(403 Forbidden)
excon.error.response
  :body          => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error>\n  <Code>AccessDenied</Code>\n  <Message>The bucket you access does not belong to you.</Message>\n  <RequestId>5D008E974B39ED0046A010FE</RequestId>\n  <HostId>xxxgitbackup.oss-cn-hangzhou.aliyuncs.com:80</HostId>\n</Error>\n"
  :cookies       => [
  ]
  :headers       => {
    "Connection"        => "keep-alive"
    "Content-Length"    => "265"
    "Content-Type"      => "application/xml"
    "Date"              => "Wed, 12 Jun 2019 05:33:11 GMT"
    "Server"            => "AliyunOSS"
    "x-oss-request-id"  => "5D008E974B39ED0046A010XX"
    "x-oss-server-time" => "33"
  }
  :host          => "xxxgitbackup.oss-cn-hangzhou.aliyuncs.com"
  :local_address => "172.18.2.xx"
  :local_port    => 36126
  :path          => "/?uploads"
  :port          => 80
  :reason_phrase => "Forbidden"
  :remote_ip     => "47.110.178.xx"
  :status        => 403
  :status_line   => "HTTP/1.1 403 Forbidden\r\n"
/opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/middlewares/expects.rb:7:in `response_call'
/opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/middlewares/response_parser.rb:9:in `response_call'
/opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/connection.rb:414:in `response'
/opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/excon-0.62.0/lib/excon/connection.rb:263:in `request'
/opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/fog-core-2.1.0/lib/fog/core/connection.rb:81:in `request'
/opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/fog-aliyun-0.3.3/lib/fog/aliyun/storage.rb:150:in `request'
/opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/fog-aliyun-0.3.3/lib/fog/aliyun/requests/storage/list_objects.rb:54:in `list_multipart_uploads'
/opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/fog-aliyun-0.3.3/lib/fog/aliyun/requests/storage/put_object.rb:76:in `put_multipart_object'
/opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/fog-aliyun-0.3.3/lib/fog/aliyun/requests/storage/put_object.rb:20:in `put_object'
/opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/fog-aliyun-0.3.3/lib/fog/aliyun/models/storage/file.rb:119:in `save'
/opt/gitlab/embedded/lib/ruby/gems/2.5.0/gems/fog-core-2.1.0/lib/fog/core/collection.rb:50:in `create'

```

**Comment by gotoworld** [comment]
When i config it with a internal oss url, but it will wrong convert it to a no-internal URL.

**Comment by benjaminguttmann-avtq** [comment]
@gotoworld : Think this is related to #30

**Comment by gotoworld** [comment]
@benjaminguttmann-avtq Thx,  it's right,  and then i will close this one
