### ISSUE TITLE
Exconn warnings

### ISSUE THREAD

**Issue by ninja-at-work** [fog/fog-aliyun#73]
Hi, when I run integration tests with `export EXCON_DEBUG=true` I get the following warnings from excon library (responsible for requests):

```
[excon][WARNING] Invalid Excon request keys: :resource, :endpoint, :location, :bucket
/Library/Ruby/Gems/2.6.0/gems/excon-0.73.0/lib/excon/connection.rb:433:in `validate_params'
/Library/Ruby/Gems/2.6.0/gems/excon-0.73.0/lib/excon/connection.rb:235:in `request'
/Library/Ruby/Gems/2.6.0/gems/fog-core-2.2.0/lib/fog/core/connection.rb:79:in `request'
/Users/i068165/Work/fog/xjfog/lib/fog/aliyun/storage.rb:153:in `request'
/Users/i068165/Work/fog/xjfog/lib/fog/aliyun/requests/storage/get_containers.rb:50:in `get_containers'
/Users/i068165/Work/fog/xjfog/lib/fog/aliyun/models/storage/directories.rb:13:in `all'
/Users/i068165/Work/fog/xjfog/spec/fog/integration_spec.rb:23:in `block (2 levels) in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:257:in `instance_exec'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:257:in `block in run'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:503:in `block in with_around_and_singleton_context_hooks'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:460:in `block in with_around_example_hooks'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/hooks.rb:481:in `block in run'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/hooks.rb:619:in `run_around_example_hooks_for'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/hooks.rb:481:in `run'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:460:in `with_around_example_hooks'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:503:in `with_around_and_singleton_context_hooks'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:254:in `run'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/example_group.rb:644:in `block in run_examples'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/example_group.rb:640:in `map'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/example_group.rb:640:in `run_examples'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/example_group.rb:606:in `run'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:121:in `map'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/configuration.rb:2058:in `with_suite_hooks'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:116:in `block in run_specs'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/reporter.rb:74:in `report'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:115:in `run_specs'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:89:in `run'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:71:in `run'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:45:in `invoke'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/exe/rspec:4:in `<main>'
[excon][WARNING] The following request keys are only valid with the associated middleware:
/Library/Ruby/Gems/2.6.0/gems/excon-0.73.0/lib/excon/connection.rb:440:in `validate_params'
/Library/Ruby/Gems/2.6.0/gems/excon-0.73.0/lib/excon/connection.rb:235:in `request'
/Library/Ruby/Gems/2.6.0/gems/fog-core-2.2.0/lib/fog/core/connection.rb:79:in `request'
/Users/i068165/Work/fog/xjfog/lib/fog/aliyun/storage.rb:153:in `request'
/Users/i068165/Work/fog/xjfog/lib/fog/aliyun/requests/storage/get_containers.rb:50:in `get_containers'
/Users/i068165/Work/fog/xjfog/lib/fog/aliyun/models/storage/directories.rb:13:in `all'
/Users/i068165/Work/fog/xjfog/spec/fog/integration_spec.rb:23:in `block (2 levels) in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:257:in `instance_exec'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:257:in `block in run'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:503:in `block in with_around_and_singleton_context_hooks'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:460:in `block in with_around_example_hooks'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/hooks.rb:481:in `block in run'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/hooks.rb:619:in `run_around_example_hooks_for'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/hooks.rb:481:in `run'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:460:in `with_around_example_hooks'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:503:in `with_around_and_singleton_context_hooks'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/example.rb:254:in `run'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/example_group.rb:644:in `block in run_examples'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/example_group.rb:640:in `map'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/example_group.rb:640:in `run_examples'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/example_group.rb:606:in `run'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:121:in `map'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/configuration.rb:2058:in `with_suite_hooks'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:116:in `block in run_specs'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/reporter.rb:74:in `report'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:115:in `run_specs'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:89:in `run'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:71:in `run'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/lib/rspec/core/runner.rb:45:in `invoke'
/Library/Ruby/Gems/2.6.0/gems/rspec-core-3.9.2/exe/rspec:4:in `<main>'
```

**Comment by xiaozhu36** [comment]
Fixed.
